name: release_darwin

on:
  release:
    types: [ published ]

jobs:
  release_darwin_amd64:
    strategy:
      matrix:
        target: [ darwin-amd64 ]
    name: Release ${{ matrix.target }}
    runs-on: macos-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch web dist
        run: |
          curl -L https://github.com/alist-org/alist-web/releases/latest/download/dist.tar.gz -o dist.tar.gz
          tar -zxvf dist.tar.gz
          rm -rf public/dist
          mv -f dist public
          rm -f dist.tar.gz

      - name: Build
        env:
          CGO_ENABLED: 1
        run: |
          os=$(echo ${{ matrix.target }} | cut -d'-' -f1)
          arch=$(echo ${{ matrix.target }} | cut -d'-' -f2)
          built_at="$(date +'%F %T %z')"
          git_author="Xhofe <i@nn.ci>"
          git_commit=$(git log --pretty=format:"%h" -1)
          version=$(git describe --abbrev=0 --tags)
          web_version=$(curl -sL "https://api.github.com/repos/alist-org/alist-web/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          mkdir -p build
          GOOS=$os GOARCH=$arch go build -o build/alist-$os-$arch \
            -ldflags "-w -s \
              -X 'github.com/alist-org/alist/v3/internal/conf.BuiltAt=$built_at' \
              -X 'github.com/alist-org/alist/v3/internal/conf.GitAuthor=$git_author' \
              -X 'github.com/alist-org/alist/v3/internal/conf.GitCommit=$git_commit' \
              -X 'github.com/alist-org/alist/v3/internal/conf.Version=$version' \
              -X 'github.com/alist-org/alist/v3/internal/conf.WebVersion=$web_version'" \
            -tags=jsoniter .

      - name: Compress
        run: |
          mkdir -p build/compress
          for i in $(find build -type f -name "alist-darwin-*"); do
            cp "$i" build/alist
            tar -czvf build/compress/"$i".tar.gz -C build alist
            rm -f build/alist
          done
          cd build/compress
          find . -type f -print0 | xargs -0 md5sum >md5-darwin-amd64.txt
          cat md5-darwin-amd64.txt

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/compress/*

  release_darwin_arm64:
    strategy:
      matrix:
        target: [ darwin-arm64 ]
    name: Release ${{ matrix.target }}
    runs-on: macos-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch web dist
        run: |
          curl -L https://github.com/alist-org/alist-web/releases/latest/download/dist.tar.gz -o dist.tar.gz
          tar -zxvf dist.tar.gz
          rm -rf public/dist
          mv -f dist public
          rm -f dist.tar.gz

      - name: Build
        env:
          CGO_ENABLED: 1
        run: |
          os=$(echo ${{ matrix.target }} | cut -d'-' -f1)
          arch=$(echo ${{ matrix.target }} | cut -d'-' -f2)
          built_at="$(date +'%F %T %z')"
          git_author="Xhofe <i@nn.ci>"
          git_commit=$(git log --pretty=format:"%h" -1)
          version=$(git describe --abbrev=0 --tags)
          web_version=$(curl -sL "https://api.github.com/repos/alist-org/alist-web/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          mkdir -p build
          GOOS=$os GOARCH=$arch go build -o build/alist-$os-$arch \
            -ldflags "-w -s \
              -X 'github.com/alist-org/alist/v3/internal/conf.BuiltAt=$built_at' \
              -X 'github.com/alist-org/alist/v3/internal/conf.GitAuthor=$git_author' \
              -X 'github.com/alist-org/alist/v3/internal/conf.GitCommit=$git_commit' \
              -X 'github.com/alist-org/alist/v3/internal/conf.Version=$version' \
              -X 'github.com/alist-org/alist/v3/internal/conf.WebVersion=$web_version'" \
            -tags=jsoniter .

      - name: Compress
        run: |
          mkdir -p build/compress
          for i in $(find build -type f -name "alist-darwin-*"); do
            cp "$i" build/alist
            tar -czvf build/compress/"$i".tar.gz -C build alist
            rm -f build/alist
          done
          cd build/compress
          find . -type f -print0 | xargs -0 md5sum >md5-darwin-arm64.txt
          cat md5-darwin-arm64.txt

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/compress/*
